"""empty message

Revision ID: fe0668452668
Revises: e3ad93b5dc5e
Create Date: 2025-01-30 00:22:12.558165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe0668452668'
down_revision = 'e3ad93b5dc5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('rating_description', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.drop_column('rating_description')
        batch_op.drop_column('rating')
        batch_op.drop_column('city')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
